# Generated by Django 4.0.4 on 2022-05-22 08:53

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='myModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('data_list', django_mysql.models.ListCharField(models.CharField(max_length=10), max_length=66, size=6)),
                ('data_object', models.JSONField(default={})),
            ],
        ),
    ]
