# Generated by Django 4.0.4 on 2022-05-27 07:01

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcMaster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(default='undefined', max_length=400)),
                ('ac_no', models.IntegerField()),
                ('ac_name', models.CharField(max_length=300)),
                ('pc_no', models.IntegerField()),
                ('pc_name', models.CharField(max_length=300)),
                ('zone', models.CharField(max_length=300)),
                ('district_no', models.IntegerField()),
                ('district_name', models.CharField(max_length=300)),
                ('mp', models.CharField(max_length=300)),
                ('mla', models.CharField(max_length=300)),
                ('date_of_updation', models.DateField(auto_now=True)),
                ('current_seat_category', models.CharField(max_length=20)),
                ('unique_name', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='myModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('data_list', django_mysql.models.ListCharField(models.CharField(max_length=10), max_length=66, size=6)),
                ('data_object', models.JSONField(default={})),
            ],
        ),
        migrations.CreateModel(
            name='DemographyDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('population', models.DecimalField(decimal_places=3, max_digits=10)),
                ('date_of_updation', models.DateField(auto_now=True)),
                ('ac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.acmaster')),
            ],
        ),
    ]
